<?php

namespace App\Filament\Newsletter\Resources\Subscribers\Schemas;

use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Schema;
use Filament\Forms\Components\Select;
use Filament\Forms;

class SubscriberForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('name'),
                TextInput::make('email')
                    ->label('Email address')
                    ->email()
                    ->required(),
                Select::make('tags')
                    ->relationship('tags', 'name')
                    ->multiple()
                    ->preload()
                    ->searchable(),
                Forms\Components\DatePicker::make('birth_date')
                    ->label('Birth Date')
                    ->native(false) // nicer picker
                    ->maxDate(now())
                    ->nullable(),

                Forms\Components\Select::make('country_code')
                    ->label('Country')
                    ->options([
                        'ALB' => 'Albania',
                        'DZA' => 'Algeria',
                        'AND' => 'Andorra',
                        'AGO' => 'Angola',
                        'AIA' => 'Anguilla',
                        'ATG' => 'Antigua and Barbuda',
                        'ARG' => 'Argentina',
                        'ARM' => 'Armenia',
                        'AUS' => 'Australia',
                        'AUT' => 'Austria',
                        'AZE' => 'Azerbaijan',
                        'BHS' => 'Bahamas',
                        'BHR' => 'Bahrain',
                        'BGD' => 'Bangladesh',
                        'BRB' => 'Barbados',
                        'BLR' => 'Belarus',
                        'BEL' => 'Belgium',
                        'BLZ' => 'Belize',
                        'BEN' => 'Benin',
                        'BTN' => 'Bhutan',
                        'BOL' => 'Bolivia',
                        'BIH' => 'Bosnia and Herzegovina',
                        'BWA' => 'Botswana',
                        'BRA' => 'Brazil',
                        'VGB' => 'British Virgin Islands',
                        'BRN' => 'Brunei',
                        'BGR' => 'Bulgaria',
                        'BFA' => 'Burkina Faso',
                        'BDI' => 'Burundi',
                        'KHM' => 'Cambodia',
                        'CMR' => 'Cameroon',
                        'CAN' => 'Canada',
                        'CPV' => 'Cape Verde',
                        'CYM' => 'Cayman Islands',
                        'CAF' => 'Central African Republic',
                        'TCD' => 'Chad',
                        'CHL' => 'Chile',
                        'CHN' => 'China',
                        'CXR' => 'Christmas Island',
                        'CCK' => 'Cocos Islands',
                        'COL' => 'Colombia',
                        'COM' => 'Comoros',
                        'COG' => 'Congo',
                        'CRI' => 'Costa Rica',
                        'HRV' => 'Croatia',
                        'CUB' => 'Cuba',
                        'CYP' => 'Cyprus',
                        'CZE' => 'Czech Republic',
                        'DNK' => 'Denmark',
                        'DMA' => 'Dominica',
                        'DOM' => 'Dominican Republic',
                        'ECU' => 'Ecuador',
                        'EGY' => 'Egypt',
                        'SLV' => 'El Salvador',
                        'GNQ' => 'Equatorial Guinea',
                        'ERI' => 'Eritrea',
                        'EST' => 'Estonia',
                        'ETH' => 'Ethiopia',
                        'FRO' => 'Faroe Islands',
                        'FJI' => 'Fiji',
                        'FIN' => 'Finland',
                        'FRA' => 'France',
                        'GAB' => 'Gabon',
                        'GMB' => 'Gambia',
                        'GEO' => 'Georgia',
                        'DEU' => 'Germany',
                        'GHA' => 'Ghana',
                        'GIB' => 'Gibraltar',
                        'GRC' => 'Greece',
                        'GRL' => 'Greenland',
                        'GRD' => 'Grenada',
                        'GUM' => 'Guam',
                        'GTM' => 'Guatemala',
                        'GGY' => 'Guernsey',
                        'GIN' => 'Guinea',
                        'GNB' => 'Guinea-Bissau',
                        'GUY' => 'Guyana',
                        'HTI' => 'Haiti',
                        'HND' => 'Honduras',
                        'HKG' => 'Hong Kong',
                        'HUN' => 'Hungary',
                        'ISL' => 'Iceland',
                        'IDN' => 'Indonesia',
                        'IND' => 'India',
                        'IRN' => 'Iran',
                        'IRQ' => 'Iraq',
                        'IRL' => 'Ireland',
                        'IMN' => 'Isle of Man',
                        'ISR' => 'Israel',
                        'ITA' => 'Italy',
                        'JAM' => 'Jamaica',
                        'JPN' => 'Japan',
                        'JEY' => 'Jersey',
                        'JOR' => 'Jordan',
                        'KAZ' => 'Kazakhstan',
                        'KEN' => 'Kenya',
                        'KIR' => 'Kiribati',
                        'KWT' => 'Kuwait',
                        'KGZ' => 'Kyrgyzstan',
                        'LAO' => 'Laos',
                        'LVA' => 'Latvia',
                        'LBN' => 'Lebanon',
                        'LSO' => 'Lesotho',
                        'LBR' => 'Liberia',
                        'LBY' => 'Libya',
                        'LIE' => 'Liechtenstein',
                        'LTU' => 'Lithuania',
                        'LUX' => 'Luxembourg',
                        'MAC' => 'Macau',
                        'MWI' => 'Malawi',
                        'MYS' => 'Malaysia',
                        'MDV' => 'Maldives',
                        'MLI' => 'Mali',
                        'MLT' => 'Malta',
                        'MHL' => 'Marshall Islands',
                        'MRT' => 'Mauritania',
                        'MUS' => 'Mauritius',
                        'MYT' => 'Mayotte',
                        'MEX' => 'Mexico',
                        'FSM' => 'Micronesia',
                        'MDA' => 'Moldova',
                        'MCO' => 'Monaco',
                        'MNG' => 'Mongolia',
                        'MNE' => 'Montenegro',
                        'MSR' => 'Montserrat',
                        'MAR' => 'Morocco',
                        'MOZ' => 'Mozambique',
                        'MMR' => 'Myanmar',
                        'NAM' => 'Namibia',
                        'NRU' => 'Nauru',
                        'NPL' => 'Nepal',
                        'NLD' => 'Netherlands',
                        'NZL' => 'New Zealand',
                        'NIC' => 'Nicaragua',
                        'NER' => 'Niger',
                        'NGA' => 'Nigeria',
                        'MKD' => 'North Macedonia',
                        'PRK' => 'North Korea',
                        'NOR' => 'Norway',
                        'OMN' => 'Oman',
                        'PAK' => 'Pakistan',
                        'PLW' => 'Palau',
                        'PAN' => 'Panama',
                        'PNG' => 'Papua New Guinea',
                        'PRY' => 'Paraguay',
                        'PER' => 'Peru',
                        'PHL' => 'Philippines',
                        'POL' => 'Poland',
                        'PRT' => 'Portugal',
                        'QAT' => 'Qatar',
                        'REU' => 'Réunion',
                        'ROU' => 'Romania',
                        'RUS' => 'Russia',
                        'RWA' => 'Rwanda',
                        'KNA' => 'Saint Kitts and Nevis',
                        'LCA' => 'Saint Lucia',
                        'VCT' => 'Saint Vincent and the Grenadines',
                        'WSM' => 'Samoa',
                        'SMR' => 'San Marino',
                        'STP' => 'São Tomé and Príncipe',
                        'SAU' => 'Saudi Arabia',
                        'SEN' => 'Senegal',
                        'SRB' => 'Serbia',
                        'SYC' => 'Seychelles',
                        'SLE' => 'Sierra Leone',
                        'SGP' => 'Singapore',
                        'SVK' => 'Slovakia',
                        'SVN' => 'Slovenia',
                        'SLB' => 'Solomon Islands',
                        'SOM' => 'Somalia',
                        'ZAF' => 'South Africa',
                        'KOR' => 'South Korea',
                        'SSD' => 'South Sudan',
                        'ESP' => 'Spain',
                        'LKA' => 'Sri Lanka',
                        'SDN' => 'Sudan',
                        'SUR' => 'Suriname',
                        'SWZ' => 'Eswatini',
                        'SWE' => 'Sweden',
                        'CHE' => 'Switzerland',
                        'SYR' => 'Syria',
                        'TWN' => 'Taiwan',
                        'TJK' => 'Tajikistan',
                        'TZA' => 'Tanzania',
                        'THA' => 'Thailand',
                        'TLS' => 'Timor-Leste',
                        'TGO' => 'Togo',
                        'TON' => 'Tonga',
                        'TTO' => 'Trinidad and Tobago',
                        'TUN' => 'Tunisia',
                        'TUR' => 'Turkey',
                        'TKM' => 'Turkmenistan',
                        'TCA' => 'Turks and Caicos Islands',
                        'TUV' => 'Tuvalu',
                        'UGA' => 'Uganda',
                        'UKR' => 'Ukraine',
                        'ARE' => 'United Arab Emirates',
                        'GBR' => 'United Kingdom',
                        'USA' => 'United States',
                        'VIR' => 'U.S. Virgin Islands',
                        'URY' => 'Uruguay',
                        'UZB' => 'Uzbekistan',
                        'VUT' => 'Vanuatu',
                        'VAT' => 'Vatican City',
                        'VEN' => 'Venezuela',
                        'VNM' => 'Vietnam',
                        'WLF' => 'Wallis and Futuna',
                        'ESH' => 'Western Sahara',
                        'YEM' => 'Yemen',
                        'ZMB' => 'Zambia',
                        'ZWE' => 'Zimbabwe',
                    ])
                    ->searchable()
                    ->nullable(),
                Toggle::make('is_active')
                    ->required(),
            ]);
    }
}
